name: Daily Shayari Generator

on:
  schedule:
    - cron: "0 5 * * *"   # daily at 05:00 UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-generative-ai==0.8.3

      - name: Generate shayari with Gemini
        env:
          GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}   # comma-separated keys
          GEMINI_MODEL: gemini-1.5-flash
        run: |
          python content_automation/generate_online_shayari.py

      - name: Commit & push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add online_shayari.json
          git commit -m "chore: daily shayari update"
          git push
